networks:
  mc-infra-connector-network:
  mc-infra-manager-network:
  mc-iam-manager-network:

services:
  mc-infra-connector:
    image: cloudbaristaorg/cb-spider:0.9.0
    pull_policy: missing
    container_name: mc-infra-connector
    platform: linux/amd64
    networks:
      - mc-infra-connector-network
    ports:
      - target: 1024
        published: 1024
        protocol: tcp
    volumes:
      - ./conf/mc-infra-connector/:/root/go/src/github.com/cloud-barista/cb-spider/conf/
      - ./data/mc-infra-connector/meta_db/:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/
      - ./data/mc-infra-connector/log/:/root/go/src/github.com/cloud-barista/cb-spider/log/
    environment:
      - PLUGIN_SW=OFF
      # - SERVER_ADDRESS=localhost
      # if you leave these values empty, REST Auth will be disabled.
      # - API_USERNAME=
      # - API_PASSWORD=
      - SPIDER_LOG_LEVEL=error
      - SPIDER_HISCALL_LOG_LEVEL=error
      # - ID_TRANSFORM_MODE=ON

  mc-infra-manager:
    image: cloudbaristaorg/cb-tumblebug:0.9.4
    container_name: mc-infra-manager
    pull_policy: missing
    platform: linux/amd64
    networks:
      - mc-infra-connector-network
      - mc-infra-manager-network
    ports:
      - target: 1323
        published: 1323
        protocol: tcp
    depends_on: 
      - mc-infra-manager-etcd
      - mc-infra-connector
    volumes:
      - ./conf/mc-infra-manager/:/app/conf/
      - ./data/mc-infra-manager/meta_db/:/app/meta_db/
      - ./data/mc-infra-manager/log/:/app/log/
    environment:
      # - TB_ROOT_PATH=/app
      - TB_SPIDER_REST_URL=http://mc-infra-connector:1024/spider
      - TB_ETCD_ENDPOINTS=http://mc-infra-manager-etcd:2379
      # - TB_ETCD_AUTH_ENABLED=true
      # - TB_ETCD_USERNAME=default
      # - TB_ETCD_PASSWORD=default
      # - TB_SQLITE_URL=localhost:3306 
      # - TB_SQLITE_DATABASE=cb_tumblebug 
      # - TB_SQLITE_USER=cb_tumblebug 
      # - TB_SQLITE_PASSWORD=cb_tumblebug 
      # - TB_ALLOW_ORIGINS=*
      # - TB_AUTH_ENABLED=true
      # - TB_API_USERNAME=default
      # - TB_API_PASSWORD=default
      # - TB_AUTOCONTROL_DURATION_MS=10000
      # - TB_SELF_ENDPOINT=localhost:1323
      # - TB_DRAGONFLY_REST_URL=http://cb-dragonfly:9090/dragonfly
      # - TB_DEFAULT_NAMESPACE=ns01
      # - TB_DEFAULT_CREDENTIALHOLDER=admin
      # - TB_LOGFILE_PATH=/app/log/tumblebug.log
      # - TB_LOGFILE_MAXSIZE=10
      # - TB_LOGFILE_MAXBACKUPS=3
      # - TB_LOGFILE_MAXAGE=30
      # - TB_LOGFILE_COMPRESS=false
      # - TB_LOGLEVEL=debug
      # - TB_LOGWRITER=both
      # - TB_NODE_ENV=development

  mc-infra-manager-etcd:
    image: gcr.io/etcd-development/etcd:v3.5.14
    container_name: mc-infra-manager-etcd
    networks:
      - mc-infra-manager-network
    ports:
      - target: 2379
        published: 2379
        protocol: tcp
      - target: 2380
        published: 2380
        protocol: tcp
    volumes: 
      - ./data/mc-infra-manager/etcd/data:/etcd-data
    entrypoint: /usr/local/bin/etcd
    command:
      - --name
      - s1
      - --data-dir
      - /etcd-data
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-advertise-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - s1=http://0.0.0.0:2380
      - --initial-cluster-token
      - tkn
      - --initial-cluster-state
      - new
      - --log-level
      - info
      - --logger
      - zap
      - --log-outputs
      - stderr
      - --auth-token
      - simple
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  mc-iam-manager:
    container_name: mc-iam-manager
    image: mc-iam-manager:local
    pull_policy: missing
    platform: linux/amd64
    networks:
      - mc-iam-manager-network
      - mc-infra-manager-network
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    depends_on:
      - mc-iam-manager-db
      - mc-iam-manager-kc
    environment:
      GO_ENV: development # production | development
      GODEBUG: netdns=go
      DEV_DATABASE_URL: postgres://mciamadmin:mciammanagerpassword@mc-iam-manager-db:5432/mciamdb
      DATABASE_URL: postgres://mciamadmin:mciammanagerpassword@mc-iam-manager-db:5432/mciamdb
      PORT: 5000
    env_file:
      - ./conf/mc-iam-manager/.env

  mc-iam-manager-db:
    container_name: mc-iam-manager-db
    image: postgres:14-alpine
    pull_policy: missing
    platform: linux/amd64
    networks:
      - mc-iam-manager-network
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - ./data/mc-iam-manager/postgres/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mciamdb
      POSTGRES_USER: mciamadmin
      POSTGRES_PASSWORD: mciammanagerpassword

  mc-iam-manager-kc:
    container_name: mc-iam-manager-kc
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.keycloak
    networks:
      - mc-iam-manager-network
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://mc-iam-manager-db:5432/mciamdb
      KC_DB_USERNAME: mciamadmin
      KC_DB_PASSWORD: mciammanagerpassword

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080

    volumes:
      - ./data/mc-iam-manager/keycloak/data/:/opt/keycloak/data/
      - ./conf/mc-iam-manager/realm-import.json:/opt/keycloak/data/import/realm-import.json
    env_file:
      - ./conf/mc-iam-manager/.env
    depends_on:
      - mc-iam-manager-db
    command: 
      - start-dev 
      - --import-realm 
      - --verbose 
      - --features=token-exchange  
      - --https-key-store-file=/opt/keycloak/conf/server.keystore
      - --https-key-store-password=password123
